last_change = 2026-08-25T09:27:19.079391Z
addr = 0x28e030
size = 0x577
name = "CNetChan_ParseNetMessageShowFilter"

[header]
name = "CNetChan_ParseNetMessageShowFilter"
addr = 0x28e030

[header.args]
