last_change = 2026-08-25T09:27:19.079447Z
addr = 0x2a7ce0
size = 0x199
name = "CNetworkMessages_ComputeOrderForPriority"

[header]
name = "CNetworkMessages_ComputeOrderForPriority"
addr = 0x2a7ce0

[header.args]
